### ISSUE TITLE
First iteration of interface-ipfs-core

### ISSUE THREAD

**Issue by noffle** [ipfs/interface-ipfs-core#18]
Here are some thoughts on the herculean task of building this out. For each section of the API (objects, blocks, etc) we

1. write up a draft api for them as a PR in this repo
2. get approval on that PR from the core js-ipfs devs
3. write PRs on js-ipfs and js-ipfs-api to match said api
4. write tests here on interface-ipfs-core for that api
5. run both js-ipfs and js-ipfs-api against the interface-ipfs-core tests from (4)

We'll need this done for the whole core api:

high priority:
- [x] objects
  - [x] draft api
  - [x] api approval
  - [x] js-ipfs support
  - [x] js-ipfs-api support
  - [x] interface-ipfs-core tests
  - [x] tests passing against js-ipfs and js-ipfs-api
- [x] blocks
  - [x] draft api
  - [x] api approval
  - [x] js-ipfs support
  - [x] js-ipfs-api support
  - [x] interface-ipfs-core tests
  - [x] tests passing against js-ipfs and js-ipfs-api
- [x] add
  - [x] draft api
  - [x] api approval
  - [x] js-ipfs support
    - [x] [refactor out filesystem pieces](https://github.com/ipfs/js-ipfs-api/issues/279)
  - [x] js-ipfs-api support
  - [x] interface-ipfs-core tests
  - [x] tests passing against js-ipfs and js-ipfs-api
- [x] cat
  - [x] draft api
  - [x] api approval
  - [x] js-ipfs support
  - [x] js-ipfs-api support
  - [x] interface-ipfs-core tests
  - [x] tests passing against js-ipfs and js-ipfs-api
- [x] get
  - [x] draft api
  - [x] api approval
  - [x] js-ipfs support
  - [x] js-ipfs-api support
  - [x] interface-ipfs-core tests
  - [x] tests passing against js-ipfs and js-ipfs-api

lower priority:
- [x] version
- [x] id
- [ ] refs
- [x] pin
- [ ] log

**Comment by diasdavid** [comment]
Thank you, I love things that look like Roadmaps! :) 

In terms of process, let's go more for:
- 1. Write up the API spec in a PR
  - 1.1 Write up the tests for that API
  - 1.2 Write up PR for js-ipfs and js-ipfs-api that apply the tests and necessary changes
  - 1.3 Tweet the API spec as needed (feeding back what is learned from writting and applying the tests)
- 2. Once happy, merge them all

**Comment by diasdavid** [comment]
Remaining (up for grabs :)):

- [ ] mfs https://github.com/ipfs/interface-ipfs-core/pull/38
- [ ] name https://github.com/ipfs/interface-ipfs-core/pull/37
- [ ] dht https://github.com/ipfs/interface-ipfs-core/pull/36

**Comment by diasdavid** [comment]
@VictorBjelkholm is handling files and DHT, name will be ms6. Closing this issue as clean up, tracking happens on the PR referenced in https://github.com/ipfs/interface-ipfs-core/issues/18#issuecomment-241209399

**Comment by diasdavid** [comment]
@VictorBjelkholm is handling files and DHT, name will be ms6. Closing this issue as clean up, tracking happens on the PR referenced in https://github.com/ipfs/interface-ipfs-core/issues/18#issuecomment-241209399

**Comment by Stebalien** [comment]
@diasdavid I think the refs API is still missing.

**Comment by alexander255** [comment]
Any information on the `refs` API? Is there any difference between `object.links(multihash)` & `refs(multihash)`?
