### ISSUE TITLE
Q: dag.get() returns links as CBOR Tags (or whatever); how to get a valid multihash?

### ISSUE THREAD

**Issue by ovx** [ipfs/interface-ipfs-core#195]
Hi,
dag.get() returns all links as Buffers (I think they are CBOR Tags), but to it would be helpful to get back the original multihashes so the response actually corresponds to the original data used when creating the node. I just can't figure out how to decode these CBOR Tags back to multihashes. Using `multihashes.toB58String(buffer)` doesn't exactly produce the correct value:

original CID of the link: `zdpuAzEszwciEA9mVc1JEyhr46S5gFF5p7AXsCTAXBHowNVEd`
vs the result of multihashes.toB58String: `dpuAzEszwciEA9mVc1JEyhr46S5gFF5p7AXsCTAXBHowNVEd`

Notice the result is one character shorter (missing 'z') and this casues issues when I want get a CID out this object later (Error: multihash length inconsistent: 0x1220cd4f14b4b817102adc0f09b2d3edb4c3720e5ff4a65b6e5871034469ff55d16e)

```js
dag.put({
  link: {
    "/": "zdpuAzEszwciEA9mVc1JEyhr46S5gFF5p7AXsCTAXBHowNVEd"
  },
}, {
  format: "dag-cbor",
  hashAlg: "sha2-256",
});

dag.get(rootCID, (err, node) => {
  // node.value.link["/"] is a Buffer, need to get a valid multihash again
  // multihashes.toB58String(node.value.link["/"]) doesn't work => produces invalid multihash
});
``

**Comment by magik6k** [comment]
The data in buffer is actually a binary serialized CID. What you want to use is https://github.com/ipld/js-cid, just passing the buffer to the constructor.

**Comment by ovx** [comment]
Thanks a lot! It works just the way I need it to.
