### ISSUE TITLE
Aegir loadFixture doesn't work with new js directory

### ISSUE THREAD

**Issue by alanshaw** [ipfs/interface-ipfs-core#213]
Hard coded to look for fixtures in `/base/node_modules/interface-ipfs-core/test/*` but since all the code was moved into a `js` directory it is not work anymore:

https://github.com/ipfs/aegir/blob/616383f749285e0319470a4b4b723e257fad9d4e/src/fixtures.js#L19

Maybe this is an aegir bug?

Maybe we should pass "interface-ipfs-core/js" for `module` here?:

https://github.com/ipfs/interface-ipfs-core/blob/9d91267ab7ab61e41c84eaa81c647cd630d83797/js/src/files.js#L30

**Comment by alanshaw** [comment]
I was able to work around this issue by adding a proxy into my `karma.conf.js`:

https://github.com/tableflip/ipfs-postmsg-proxy/blob/7cbff38e8e38bcc4c8deef3aeeefc9d665b6c9f2/karma.conf.js#L21-L24

**Comment by alanshaw** [comment]
`js-interface-ipfs-core` anyone?

**Comment by diasdavid** [comment]
ah! I missed this issue but I fixed this problem. It's all good now :)

**Comment by alanshaw** [comment]
💥 https://github.com/ipfs/aegir/commit/66d99502664adae66e8be4a09145a4117e35166d thanks!
