### ISSUE TITLE
file.content is a stream and toString does not work

### ISSUE THREAD

**Issue by kevinsimper** [ipfs/interface-ipfs-core#226]
Is it a mistake that it tries to do a `file.content.toString()` when the file.content is a stream.

https://github.com/ipfs/interface-ipfs-core/blame/master/SPEC/FILES.md#L333

![image](https://user-images.githubusercontent.com/1126497/36788240-6b77e0a8-1c8d-11e8-83af-f54b82ecb854.png)

I can easily fix it if we agree :)

**Comment by diasdavid** [comment]
@kevinsimper the line you pointed to is doing `file.path.toString()`, not _content_.

**Comment by kevinsimper** [comment]
@diasdavid Yes, that is probrably another mistake as the comment says above `
// write the file's path and contents to standard out`
https://github.com/ipfs/interface-ipfs-core/blame/master/SPEC/FILES.md#L331

**Comment by diasdavid** [comment]
@kevinsimper if you want to get a buffer, use `ipfs.files.get` instead

**Comment by diasdavid** [comment]
Thanks for fixing with #237 <3
