### ISSUE TITLE
ipfs.add failure~~~!!!

### ISSUE THREAD

**Issue by kelvv** [ipfs/interface-ipfs-core#250]
#####  js script:

```
const IPFS = require('ipfs')
const node = new IPFS()
const fs = require('fs')

node.on('ready', () => {
  console.log('Your node is now ready to use ')

  const files = [
    fs.readFileSync(process.cwd() + '/kelvv.cs')
  ]

  node.files.add(files, (err, files) => {
    if (err) { console.log(err) }
    console.log(files)
    // 'files' will be an array of objects containing paths and the multihashes of the files added
  })

  // stopping a node
  node.stop(() => {
    console.log('node is now offline')
  })
})
```

##### I got following result:
```
Your node is now ready to use 
node is now offline
[ { path: 'QmeVh3qKsZ5SMGaHwQBFbRLMz3AzGthBUEXqJPcCP2J5Rq',
    hash: 'QmeVh3qKsZ5SMGaHwQBFbRLMz3AzGthBUEXqJPcCP2J5Rq',
    size: 26 } ]
```

but , I  access 'https://ipfs.io/ipfs/QmeVh3qKsZ5SMGaHwQBFbRLMz3AzGthBUEXqJPcCP2J5Rq' , failure ,  no content return 

please help me~!

**Comment by VictorBjelkholm** [comment]
Correct please to ask for help with the javascript implementation would be over at github.com/ipfs/js-ipfs

But none the less, you're stopping the daemon even before the files have been added. You'll need to remove the `stop` statement if you want the files to be available for others to fetch.

**Comment by travisperson** [comment]
This issue has been moved to https://github.com/ipfs/js-ipfs/issues/1289.

Closing
