### ISSUE TITLE
MFS ipfs.files.cp arguments

### ISSUE THREAD

**Issue by achingbrain** [ipfs/interface-ipfs-core#262]
What's the thinking behind the `ipfs.files.cp` arguments?  Specifically why is the first argument an array?

```javascript
ipfs.files.cp([sourceFile, destinationFile], callback)
```

It could be more straightforward as:

```javascript
ipfs.files.cp(sourceFile, destinationFile, callback)
```

I suppose maybe you'd want to imitate the unix `cp` command and support both the above and:

```javascript
ipfs.files.cp(...sourceFiles, destinationDirectory, callback)
```

Obviously JavaScript doesn't support left-variadic functions so you'd have to emulate it by interrogating `arguments` but that's an implementation detail.

**Comment by diasdavid** [comment]
👍 on removing the array proposal too.

**Comment by achingbrain** [comment]
Great, I'll put a PR together tomorrow.

**Comment by achingbrain** [comment]
See #277 for more on this.
