### ISSUE TITLE
Mention that files.add has a pin option

### ISSUE THREAD

**Issue by Powersource** [ipfs/interface-ipfs-core#294]
To quote lidel's code in irc:
`
ipfs.files.add(Buffer.from('auto-pin')).then(results => ipfs.pin.ls(results[0].hash).then(pins => console.dir(pins))).catch(console.error)
`
vs.
`
ipfs.files.add(Buffer.from('no-auto-pin'), {pin: false}).then(results => ipfs.pin.ls(results[0].hash).then(pins => console.dir(pins))).catch(console.error)
`

Should also mention that it automatically pins. (Do I have to add recursively to get it to pin recursively?)

**Comment by alanshaw** [comment]
@Powersource `pin.add` has a `recursive` option - the recursive add does not effect what happens when you pin.

Would you be willing to send a PR to the docs here?

**Comment by Powersource** [comment]
https://github.com/ipfs/interface-ipfs-core/pull/297
