### ISSUE TITLE
Naming of files uploaded to IPFS

### ISSUE THREAD

**Issue by ondratra** [ipfs/interface-ipfs-core#299]
Hello, 
I am trying to create very simple prototype that will upload file `myFile.md" to IPFS and then downloads it in browser with filename preserved.

From what I learned I need to create folder on IPFS otherwise filename is not preserved. But I fail in achieving this. 

Unfortunately I was not able to find example on this(I looked at examples and tests). Can somebody point me to the right direction, please? 

My current code:
```
const fileName = "myFile.md";
const fileData = "some data"; 

// upload
let filesToIpfs = [{
    path: 'myFolder/' + fileName,
    content: Buffer.from(fileData)
}];

ipfs.files.add(filesToIpfs, (error, ipfsHash) => {
    console.log(ipfsHash);

    // here I got all info I need - great
    let fileHash = ipfsHash[0].hash; // hash of data
    let filePath = ipfsHash[0].path; // == "myFolder/" + fileName
});

...

// download
ipfs.files.cat(fileHash, (error, result) => {
    console.log(result); // only data - no filename :(
});
```

**Comment by ondratra** [comment]
Also accesing `https://ipfs.io/ipfs/FILE_HASH/myFolder/myFile.md` doesn't work and returns 
```ipfs resolve -r /ipfs/FILE_HASH/myFolder/myFile.md: no link named "a" under FILE_HASH```

**Comment by travisperson** [comment]
The filename is stored in the directory object, which will be the second object returned in `ipfsHash`.

That object may look like the following

```
{
  "data": <Buffer 08 01>,
  "links": [
    {
      "name": "myFile.md",
      "size": 17,
      "multihash": "QmVv4Wz46JaZJeH5PMV4LGbRiiMKEmszPYY3g6fjGnVXBS"
    }
  ],
  "multihash": "QmSTEjcAU1GXkiWUcB2RAPA5WXMnLceyiqGDdT1bz27fs2",
  "size": 72
}
```

The name `myFolder` will not appear anywhere unless you wrap the add as well.

**Comment by ondratra** [comment]
thx for comment! 

can you show me how to "wrap the add" for folder, please? I never get object in this format(using `ipfs.files.add` and `ipfs.files.cat`).

When using `ipfs.files.add` resulting object `ipfsHash` looks like this: (folder name is this example is `a`)
```
[
    {
        "path": "a/tmp.md",
        "hash": "QmSZgb9zoaFp3mxqYR7Xu9PJUFrEcGzZuXY5zyKY7qXHPa",
        "size": 28
    },
    {
        "path": "a",
        "hash": "QmSR1fRb3Zs5jbHwCXQozHayMW9muRugoPnTpw3Zz7zPbR",
        "size": 80
    }
]
```
And when I use `ipfs.files.cat` I get:
```
{
    "type": "Buffer",
    "data": [
        116,
        104,
        105,
        115,
        32,
        105,
        115,
        32,
        100,
        111,
        99,
        117,
        109,
        101,
        110,
        116,
        32,
        58,
        41,
        10
    ]
}
```

**Comment by travisperson** [comment]
Whatever you are logging is a `Buffer`, you will need to call `toString()` on it to get it into a string.

The example I showed above was retrieving a folder (ex:  `QmSR1fRb3Zs5jbHwCXQozHayMW9muRugoPnTpw3Zz7zPbR`), using `ipfs.object.get`.

**Comment by alanshaw** [comment]
@ondratra you can use the `wrapWithDirectory` option when calling `files.add` to put your content in a directory. See https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#filesadd

Does that answer your question?

**Comment by alanshaw** [comment]
@ondratra shout if you need anything else :)
