### ISSUE TITLE
DAG API example is wrong

### ISSUE THREAD

**Issue by richardschneider** [ipfs/interface-ipfs-core#307]
The `dag.put` example in https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/DAG.md is wrong. 

    const obj = { simple: 'object' }
    ipfs.dag.put(obj, { format: 'dag-cbor', hashAlg: 'sha3-512' }, (err, cid) => {
        console.log(cid.toBaseEncodedString())
       // zdpuAzE1oAAMpsfdoexcJv6PmL9UhE8nddUYGU32R98tzV5fv
    })

The expected cid of `zdpuAzE1oAAMpsfdoexcJv6PmL9UhE8nddUYGU32R98tzV5fv` decodes as `base58btc cidv1 dag-cbor sha2-256 Qmc9E2LoddF1MdSVzYaaFxr6iByWSa2Q7pSpiKHcV4drm6`.

The hash algorithm should be `sha3-512` not `sha2-256`.

**Comment by richardschneider** [comment]
This is related to https://github.com/ipld/js-ipld/issues/82

**Comment by alanshaw** [comment]
@PascalPrecht any chance you can send a PR to fix this up? 😉 🙏

**Comment by PascalPrecht** [comment]
On my way!

**Comment by PascalPrecht** [comment]
> The hash algorithm should be sha3-512 not sha2-256.

Well **actually**, the algorithm is right, but the hash should be different. I guess the example should demonstrate how to override the default hash algorithm (which is already sha-256). I'll send a PR to update the hash

**Comment by PascalPrecht** [comment]
@richardschneider See linked PR. Here's to verify: http://cid-utils.ipfs.team/#zBwWX9ecx5F4X54WAjmFLErnBT6ByfNxStr5ovowTL7AhaUR98RWvXPS1V3HqV1qs3r5Ec5ocv7eCdbqYQREXNUfYNuKG
