### ISSUE TITLE
Key Export

### ISSUE THREAD

**Issue by abdulwahidgul24085** [ipfs/interface-ipfs-core#340]
Hi, when I try to export my key(s) from js code, it gives me an undefined type error.

This is my code

var ipfsAPI = require('ipfs-api')

// connect to an ipfs daemon API server
var ipfs = ipfsAPI('localhost','5001',{'portocol':'http'})

ipfs.key.gen('uzair1995', {
    type: 'rsa',
    size: 2048
}, )

ipfs.key.list((err, keys) => console.log(keys))

ipfs.key.export('uzair1995', 'password', (err, pem) => console.log(pem))

When I log the error, I get the following error 

![image](https://user-images.githubusercontent.com/6042059/43525346-faefc36c-95ba-11e8-96cc-fc24f1682d91.png)

Help needed, Thanks in advance.

**Comment by richardschneider** [comment]
From the port number, I assume that the `daemon` is go-ipfs.  It does not support key import/export commands.

**Comment by alanshaw** [comment]
Hopefully that answers your question @abdulwahidgul24085 :D
