### ISSUE TITLE
swarm.connect timeout?

### ISSUE THREAD

**Issue by achingbrain** [ipfs/interface-ipfs-core#381]
It would be really useful to have a timeout when trying to dial a remote peer.

```javascript
await ipfs.swarm.connect(multiaddr, {
  timeout: 5000 // ms
})
// if the timeout is reached, throw and error with a .code property with the value 'ETIMEOUT'
```

**Comment by diasdavid** [comment]
We really need to get the Cancellable Requests / Timeouts story on. I hear that async/wait & promises make that so much easier :) => #58

**Comment by diasdavid** [comment]
Let's follow up on timeouts on #58
