### ISSUE TITLE
🌟 interface-ipfs-core Updates and Changelog 📣

### ISSUE THREAD

**Issue by diasdavid** [ipfs/interface-ipfs-core#55]
Ohai! 

We are creating this issue in order to have a channel with you, the IPFS users, to communicate interface changes on js-ipfs and js-ipfs-api. Pretty soon we will also have changelogs automatically generated upon each release, but this channel serves the purpose of notifying before hand of such change and also invite you, the user, to let us know ways to make the API better.

Once interface-ipfs-core reaches 1.0.0, the interface changes will be less frequent.
#### If you want to get notified to js-ipfs and js-ipfs-api interface changes (real updates and proposed updates), please subscribe to this issue

Thank you!

**Comment by diasdavid** [comment]
First update: 

**ipfs.files.get** spec was complete and js-ipfs and js-ipfs-api were made compliant.[check the API here] (https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#get)

**Comment by diasdavid** [comment]
📣

**ipfs.files.add** will be refactored to become more convenient for developers, see proposal here: https://github.com/ipfs/interface-ipfs-core/issues/29

**Comment by diasdavid** [comment]
📣

**ipfs.block** is being upgraded implementation wise, so that it matches the API spec. Follow here https://github.com/ipfs/interface-ipfs-core/pull/64

**Comment by dignifiedquire** [comment]
📣

**ipfs.swarm.addrs* was upgraded to return an array of [`PeerInfo`](https://github.com/libp2p/js-peer-info)s. See #73 for details

**Comment by diasdavid** [comment]
# New PubSub API added https://github.com/ipfs/interface-ipfs-core/tree/master/API/pubsub

**Comment by diasdavid** [comment]
# 📣 

- [ ] Forcing `data` to be Buffer, instead of accepting Strings and converting them to buffers silently - https://github.com/ipld/js-ipld-dag-pb/pull/11

**Comment by diasdavid** [comment]
📣

Important for everyone to chime in https://github.com/ipfs/interface-ipfs-core/issues/126
