### ISSUE TITLE
Files API add example has a bug

### ISSUE THREAD

**Issue by pcowgill** [ipfs/interface-ipfs-core#598]
In the example [here](https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#add), content wouldn't be defined.

```js
const files = [{
  path: '/tmp/myfile.txt',
  content: 'ABC'
}]

for await (const result of ipfs.add(content)) {
  console.log(result)
}
```

**Comment by achingbrain** [comment]
Thanks for pointing it out - it'll be fixed by #597
