### ISSUE TITLE
Add CI (travis + circle ci)

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/interface-ipfs-core#6]
So that at least linting is run, in the future we could even clone all repos that should adhere to the spec and run them as a bonus

**Comment by diasdavid** [comment]
👍 to that (cloning all the repos will be a heck of a job though, imagine when there is several implementations in several languages and we need to set up the envs for all of them)

**Comment by harlantwood** [comment]
Probably not so bad, as the other repos have "recipes" in their own CI config files...

**Comment by noffle** [comment]
+1 to linting. Let's make cloning + testing all repos a separate issue and maybe a post-1.0.0 goal?

**Comment by diasdavid** [comment]
CI added https://github.com/ipfs/interface-ipfs-core/pull/52 :🎉

We will keep the testing happening each implementation repo, following the `interface/abstract-` class of interfaces.
