### ISSUE TITLE
rename `src` folder to `test`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/interface-ipfs-core#65]
> The confusing part here is that the tests are in src/ and not in test/. It took me a while to look into that directory, it's not an intuitive place. Is it possible to put the tests in test/ like every JS project?
> https://github.com/ipfs/js-ipfs-api/issues/325#issuecomment-243344037 @haadcode 

We have had the tests in src because this is a 'module', but if it makes sense for everyone, we can have the folder being exposed by the package.json being the `test` folder, avoiding the confusion.

👍 by me, anyone has anything against?

**Comment by dignifiedquire** [comment]
I find it confusing if it is in the `test` folder in here, given that there is no source. So I am :-1: on this change.

**Comment by haadcode** [comment]
I would really like see this to change. `src` is not the *source* for this module. It only has tests, so `test` is the natural place for that code. 

Why I brought this up is that every time I can't find documentation for a function, I go and look at the tests. Finding the tests for `js-ipfs-api` is extremely frustrating as it is now. I've done this multiple times and it happens every time. Mentioning it in the README ("Look for the tests in the src/ directory") is not a solution either as it'll be buried in the README.

Always think: *What is the shortest path to the information being looked for?*

**Comment by RichardLitt** [comment]
I am 👍 for this. As @dignifiedquire, there is no source; putting tests in `src` just to satisfy that requirement seems backward logic for me. Not all modules have to be the same.

**Comment by diasdavid** [comment]
This module is a `test suite`, the source of the `test suite` sits on its `src` folder, there are no tests to test the `test suite`. Hope this clarifies, closing.
