### ISSUE TITLE
Does this interface expose corenet.Dial?

### ISSUE THREAD

**Issue by prashcr** [ipfs/interface-ipfs-core#86]
Referring to https://github.com/ipfs/examples/tree/master/examples/api/service

I was wondering if there was any way to connect to a certain peer and receive a stream via a client library (js-ipfs-api) as with the corenet.Dial function in Go?

**Comment by diasdavid** [comment]
Hi @prashcr. On the ipfs-core API level, no, we only expose the swarm API which dials to other nodes but doesn't return the pipe, it gets used by IPFS. However, libp2p does expose that feature and libp2p is exposed in js-ipfs (ipfs.libp2p). 

See https://github.com/ipfs/js-libp2p-ipfs

Are you looking to accomplish this in Go or JavaScript?

**Comment by prashcr** [comment]
I'd like to accomplish it in JavaScript. Hmm, the module seems to be what I'm after, thanks!
